### ISSUE TITLE
No display gradient color of line with a set of equally series data

### ISSUE THREAD

**Issue by hungvh1904** [highcharts/highcharts-ios#149] opened 2018-12-28 04:12 UTC
I set gradient line color with this code
plotOptions.area.lineColor = HIColor(linearGradient: ["x1" : 0, "x2" : 1, "y1" : 0 , "y2" : 0], stops: [[0, "rgb(20,137,226)"], [1, "rgb(9,191,239)"]])

It works well with data as [1, 2, 3, 6, 5]
but with equally series data as [5, 5, 5, 5], have no line displaying.
This issue appears on both Highchart js / ios/ android

Please check this example http://jsfiddle.net/Fusher/2Gzkd/3/
and change data to: [5, 5, 5, 5, 5, 5]

**Comment by pawelfus** [comment] 2018-12-28 10:10
Hi @hungvh1904 

Thank your for reporting the issue. This is direct issue in the engines we can not fix: https://github.com/highcharts/highcharts/issues/1677 (reported as radial gradient, but it's a general issue with gradients).

As per Kacper's comment (https://github.com/highcharts/highcharts/issues/1677#issuecomment-166645181), you can use relative gradient (x/y values in pixels, not 0-1) which is free of this issue: http://jsfiddle.net/BlackLabel/cm5406az/ (400 in this demo means 400px).

Closing as duplicate of https://github.com/highcharts/highcharts/issues/1677

**Closed by pawelfus** 2018-12-28 10:10 UTC
