### ISSUE TITLE
PDF export issue is back

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#286] opened 2020-02-04 09:43 UTC
@sebastianbochan @ihnatmoisieiev 

The PDF export issue is back - PDF export **sometimes** is not possible. If I call

`[chartView exportToPDF];`

I see the PDF appearing in the chart area, but no way to save the file. This happens not all the time, sometimes the `exportToPDF` doesn't do anything at all, but the screen dims slightly, and I can still touch the chart area. If I call `exportToPDF` again, then the PDF appears in the chart area, but without any saving options.

https://github.com/highcharts/highcharts-ios/issues/213

**Comment by ihnatmoisieiev** [comment] 2020-02-04 09:50
Hello @skuske,

thank you for the reporting. Could you please attach some simple demo that demonstrates the issue?

**Comment by skuske** [comment] 2020-02-04 09:52
@ihnatmoisieiev 

That is difficult. I am trying at the moment, but it only appears in our production app. What I found so far is: if there's only one series in the chart, then the PDF export works fine, but once there are more series included, it fails.

**Comment by skuske** [comment] 2020-02-04 09:56
@ihnatmoisieiev 

And: it does not appear all the time. Sometimes it works just fine, sometimes it does not. I have no idea how to properly reproduce the issue, neither how to create a sample project... :o(

**Comment by skuske** [comment] 2020-02-04 09:59
I attach a screen video showing the issue. See attached zip file.

On the first click of the PDF export menu item, nothing happens, the screen only dims slightly. On the second click the PDF appears, but within the chart area, and no way to save the file.

[pdf-issue.mov.zip](https://github.com/highcharts/highcharts-ios/files/4152562/pdf-issue.mov.zip)

**Comment by skuske** [comment] 2020-02-04 10:05
@ihnatmoisieiev 

Maybe this is some kind of timing or threading issue, where the framework needs some more time to generate the PDF. It then fails to display the saving options if the PDF generation has not completed yet.

Just an idea, but that would explain why it works with simple line charts, but not with charts where several series are included.

**Comment by skuske** [comment] 2020-02-05 09:28
@ihnatmoisieiev 

Have you checked my screen cast? I'd like to remove it from my post then.

It is always so that on the first call of `exportToPDF`, nothing really happens, but on the second or third attempt the PDF appears within the chart area.

**Comment by ihnatmoisieiev** [comment] 2020-02-05 09:49
Hello @skuske,
yes, I've checked it. It's strange. We will look on it before the next release.

I also noticed that it happens on the iPad. Have you checked it on the iPhone?

**Comment by skuske** [comment] 2020-02-05 09:53
Hello @ihnatmoisieiev 

that sounds like you were able to reproduce this issue?

I haven't tested this on an iPad. It always appears on our iPhone devices, no matter what type. We develop on an iPhone XS and there we see the issue all the time.

**Comment by ihnatmoisieiev** [comment] 2020-02-05 10:31
@skuske no, I can't reproduce at the moment. It works properly for me.

What version of iOS do you have on devices?

**Comment by skuske** [comment] 2020-02-05 10:33
@ihnatmoisieiev 

iOS 13.3.1, but the issues also occurs on devices with older 13.x versions.

**Comment by ihnatmoisieiev** [comment] 2020-05-19 18:13
@skuske does the issue still appear for you? Can I close it?

**Closed** 2020-05-19 18:16 UTC
