### ISSUE TITLE
hiboost is not working

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts-ios#215] opened 2019-07-29 10:55 UTC
I have create option object like that

var options:HIOptions {
        let boost = HIBoost()
        boost.useGPUTranslations = NSNumber(value:true)
        
        let option = HIOptions()
        option.boost = boost
        let time =  HITime()
        time.timezone = TimeZone.autoupdatingCurrent.identifier // "Asia/Kolkata"
        option.time = time
        option.exporting = HIExporting()
        option.exporting.enabled = NSNumber(value:false)
        
        let credit = HICredits()
        credit.enabled = NSNumber(value:false)
        option.credits = credit
        return option
    }

when there is data points more than 1000. It was unable to load. Please send me solution asap.

**Comment by sebastianbochan** [comment] 2019-07-29 13:43
Im closing this ticket as duplicate of https://github.com/highcharts/highcharts-ios/issues/214

**Closed by sebastianbochan** 2019-07-29 13:43 UTC
