### ISSUE TITLE
How to Export the chart or Data in Pdf or Excel ?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#213] opened 2019-07-24 06:45 UTC
![Screenshot 2019-07-24 at 12 13 43 PM](https://user-images.githubusercontent.com/48505333/61771085-7fe40000-ae0c-11e9-8133-7539ae9fa84f.png)
How to Export Pdf or Excel When I click on the Export button.

**Comment by ihnatmoisieiev** [comment] 2019-07-24 07:58
Hello @barotbhavesh,

closing as duplicate of https://github.com/highcharts/highcharts-ios/issues/49.

**Comment by barotbhavesh** [comment] 2019-07-24 10:53
@ihnatmoisieiev PDF not working when I Click to Slide Menu then pop will open and then select PDF share but not any response 

![Screenshot 2019-07-24 at 3 28 20 PM](https://user-images.githubusercontent.com/48505333/61788230-3ce75400-ae2f-11e9-9e9e-bf257875891b.png)

After pop will open click to PDF Share Looks Like this

![Screenshot 2019-07-24 at 3 28 26 PM](https://user-images.githubusercontent.com/48505333/61788281-5b4d4f80-ae2f-11e9-9976-afb548f3da67.png)

**Comment by ihnatmoisieiev** [comment] 2019-07-25 06:50
@barotbhavesh thank you for the reporting.

It's opening a PDF, but there is no share option.

I will report the issue.

You can use image sharing in the meantime.

**Comment by barotbhavesh** [comment] 2019-07-26 06:06
@ihnatmoisieiev  one more question can it possible to Image or CSV both are in one share option?
when I selected that share option then both CSV or Image in a single file save on device?

**Comment by ihnatmoisieiev** [comment] 2019-07-26 06:16
@barotbhavesh it is not possible.

**Comment by barotbhavesh** [comment] 2019-07-26 06:19
okay, thank you so much and how much time you need to solve the PDF share Bug @ihnatmoisieiev?

**Comment by skuske** [comment] 2019-09-02 07:35
@ihnatmoisieiev

I am seeing the same PDF issue. When exactly will it be fixed? Can PDF export be disabled programmatically unless this is resolved?

**Comment by skuske** [comment] 2019-09-02 12:56
@barotbhavesh 

How do you use the export feature although PDF export is not working? Did you find any workaround? Thanks.

**Comment by ihnatmoisieiev** [comment] 2019-09-02 13:30
@skuske @barotbhavesh the issue will be fixed in the next release.

**Comment by skuske** [comment] 2019-09-02 13:45
@ihnatmoisieiev 

Thanks - when will the next release be available?

**Comment by ihnatmoisieiev** [comment] 2019-09-11 05:56
@skuske @barotbhavesh the newest release is available and fixes the issue.

**Comment by skuske** [comment] 2019-09-12 07:10
@ihnatmoisieiev Everything works fine now. Thanks. :o) I think you can close this.

**Closed** 2019-09-24 10:39 UTC
Labels: bug, question
