### ISSUE TITLE
tooltip view do not get dismiss once it was present

### ISSUE THREAD

**Issue by guptavirendra** [highcharts/highcharts-ios#217] opened 2019-08-13 13:23 UTC

**Comment by guptavirendra** [comment] 2019-08-13 13:31
Once a tooltip was appeared then it was not removed.

**Comment by ihnatmoisieiev** [comment] 2019-08-15 13:20
Hello @guptavirendra,

could you provide more info and share your chart options?

**Comment by guptavirendra** [comment] 2019-08-16 09:09
Sure

**Comment by guptavirendra** [comment] 2019-08-26 07:16
extension HIOptionProvidable {
    var options:HIOptions {
        let boost = HIBoost()
        boost.useGPUTranslations = NSNumber(value:true)
        
        let option = HIOptions()
        option.boost = boost
        let time =  HITime()
        time.timezone = TimeZone.autoupdatingCurrent.identifier // "Asia/Kolkata"
        option.time = time
        option.exporting = HIExporting()
        option.exporting.enabled = NSNumber(value:false)
        
        let credit = HICredits()
        credit.enabled = NSNumber(value:false)
        option.credits = credit
        return option
    }
}

**Comment by guptavirendra** [comment] 2019-08-26 07:19
When any tooltip was present and I was trying to dismiss tooltipView while tapping on the screen. i do not get removed.

**Comment by guptavirendra** [comment] 2019-08-27 06:03
Please do response.

**Comment by guptavirendra** [comment] 2019-08-27 06:04
![Image-1 (1)](https://user-images.githubusercontent.com/891554/63744944-80196480-c8be-11e9-831e-0f25614185d7.jpg)
Once the tooltip was presented after tapping outside the tooltip it was not get dismissed.

**Comment by ihnatmoisieiev** [comment] 2019-08-27 07:01
@guptavirendra options you provided in this [comment](https://github.com/highcharts/highcharts-ios/issues/217#issuecomment-524746574) is not correct. I can't reproduce your problem at the moment. Please send all your config of `HIOptions` object.

**Comment by guptavirendra** [comment] 2019-08-27 09:17
[MCGraphBaseview.swift.zip](https://github.com/highcharts/highcharts-ios/files/3545288/MCGraphBaseview.swift.zip)
Please find this complete classs

**Comment by guptavirendra** [comment] 2019-08-27 13:20
Did you get a chance to have a look on it.

**Comment by guptavirendra** [comment] 2019-08-28 05:53
Please do response

**Comment by guptavirendra** [comment] 2019-08-28 05:55
In the above zip code there is a class ToolTip provider. Please have a look into

**Comment by ihnatmoisieiev** [comment] 2019-08-28 08:10
@guptavirendra I get the following chart from your options: 

![Screen](https://user-images.githubusercontent.com/11294008/63836927-d055fc80-c97a-11e9-999c-4d48b8298e88.png)

Please try the simplest options from [README](https://github.com/highcharts/highcharts-ios/blob/master/README.md) and try to reproduce your issue: 

```
let options = HIOptions()

let chart = HIChart()
chart.type = "column"
options.chart = chart

let title = HITitle()
title.text = "Demo chart"
options.title = title

let series = HIColumn()
series.data = [49.9, 71.5, 106.4, 129.2, 144, 176, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
options.series = [series]
```

If you will be able to reproduce your problem, please send options in the same format as above.

**Comment by ihnatmoisieiev** [comment] 2019-09-07 06:48
@guptavirendra could I close the issue?

**Comment by guptavirendra** [comment] 2019-09-07 08:09
Close it

**Closed** 2019-09-09 06:26 UTC
Labels: question
