### ISSUE TITLE
Crash: dyld[659]: Library not loaded: @rpath/Highcharts.framework/Highcharts

### ISSUE THREAD

**Issue by skuske** [highcharts/highcharts-ios#405] opened 2022-11-11 07:21 UTC
I am seeing this crash on every project that contains Highcharts:

<img width="976" alt="crash" src="https://user-images.githubusercontent.com/12996815/201287543-6715890c-ecd2-4ecd-8da2-e5283d474f41.png">

This even happens in a simple test project. The project builds fine, but once running on a device, it crashes on start up.

Xcode Version 14.1 (14B47b)
Mac M1
Highcharts 10.3.1
Adding framework via Cocoapods

**Comment by ihnatmoisieiev** [comment] 2022-11-20 11:53
Hello @skuske,
thank you for the reporting.
We will investigate the issue and come back to you as soon as possible.

**Comment by ihnatmoisieiev** [comment] 2022-12-08 16:54
Hello @skuske,
we have tried it but can't reproduce the issue.
Could you please run a below simple project and check it?
Thank you.
[Highcharts Cocoapods Crash.zip](https://github.com/highcharts/highcharts-ios/files/10187640/Highcharts.Cocoapods.Crash.zip)

**Comment by skuske** [comment] 2022-12-08 17:06
@ihnatmoisieiev 

Thanks, the sample project works.

I have now added Highcharts iOS manually to my project, without using Cocoapods, and that works, too. Too much hassle to get it working via Cocoapods, I already spent hours debugging that. So, for now I am no longer using Cocoapods and it works fine.

**Comment by ihnatmoisieiev** [comment] 2022-12-08 17:08
@skuske 
thanks for you response.
Looks like with Cocoapods it works fine now.
Could I close the issue?

**Closed** 2022-12-08 17:09 UTC
