### ISSUE TITLE
Invalid Privacy Manifest File

### ISSUE THREAD

**Issue by jobinsjohn** [highcharts/highcharts-ios#434] opened 2024-03-20 12:45 UTC
<img width="770" alt="Screenshot 2024-03-20 at 8 44 10 AM" src="https://github.com/highcharts/highcharts-ios/assets/3398498/24c69e5c-e52c-4d33-bb5a-a6c3878aae24">

I got the above message from Apple when i submitted the latest version of my App. I am using version 11.4.0 in my latest release.

**Comment by ihnatmoisieiev** [comment] 2024-03-24 07:13
Hello @jobinsjohn,
thanks for the reporting. I hope it will be fixed next release.

**Comment by ihnatmoisieiev** [comment] 2024-04-11 18:44
Hello @jobinsjohn,
v11.4.1 has been released. Please check and close the issue if everything is good.
Thank you.

**Comment by 7-plus-t** [comment] 2024-04-12 07:24
Hi @ihnatmoisieiev 

Sadly, the privacy manifest is still invalid:
`Missing an expected key: 'NSPrivacyCollectedDataTypes'`

You can verify it by adding the SDK to any app, archive the app and then in the Xcode Organizer ctrl-right click the archive and select "Generate Privacy Report".

As far as I understand the requirements, all 4 keys need to be defined in the file, even if there are no values to be declared:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
</dict>
</plist>
```

Cheers

**Comment by ihnatmoisieiev** [comment] 2024-04-13 08:48
Hello @7-plus-t,
thanks for your attention.
The issue is fixed and the correct Privacy Manifest file will be available starting the next release.

**Comment by MikolajMichalczak** [comment] 2024-05-10 11:59
Hi all!
We've just released a new version (11.4.1.1) which addresses this issue. Your feedback is greatly appreciated.

**Comment by 7-plus-t** [comment] 2024-05-13 12:05
Hi @MikolajMichalczak 
I can confirm that with version 11.4.1.1 the privacy manifest passes the Xcode checks.

FYI: SPMs allow only three-integer version numbers (e.g. 11.4.2, not 11.4.1.1) as described in the [documentation](https://developer.apple.com/documentation/packagedescription/version). I had to install it using the commit hash instead, as Xcode does not allow entering a four-integer version.

**Comment by MikolajMichalczak** [comment] 2024-05-13 15:28
Thanks for the information @7-plus-t , and I understand. This version was an unexpected patch, and it's also crucial for Android wrapper versions to align with upcoming core library versions. We'll definitely take this into account for any future similar cases.

**Closed by MikolajMichalczak** 2024-05-13 15:28 UTC
Labels: enhancement
