### ISSUE TITLE
Negative value not show Pie chart.

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#256] opened 2019-11-04 10:03 UTC
I have a dynamic response with negative value need to display negative value but currently pie chart generate positive value chart but not show negative value so please help me to generate negative + positive value pie chart.

Thank you in Advance

**Comment by ihnatmoisieiev** [comment] 2019-11-04 10:16
Hello @barotbhavesh,

please share your chart options and example data.

**Comment by barotbhavesh** [comment] 2019-11-04 11:27
Demo Data to display in Pia chart 

{"ResponseStatus":true,"ErrorData":null,"Message":"","ResponseData":[{"IsDetailTransaction":false,"Title":"Year to Date","Data":[{"PerValue":42.48,"Key":"Other","Value":69426.35},{"PerValue":-19.37,"Key":"Parts","Value":-270626.24},{"PerValue":-22.04,"Key":"Labor","Value":-228127.36},{"PerValue":0.09,"Key":"Oil Disposal Fees","Value":105.99},{"PerValue":-1.16,"Key":"Sales Tax","Value":-18992.62},{"PerValue":0,"Key":"Total","Value":-448213.88}],"TitleValue":"MTD Variance"}]}

Create PIE chart with this function

    func drowChartsForCurrentMonth() {
        let options = HIOptions()
        
        let exporting = HIExporting()
        exporting.enabled = false
        
        let chart = HIChart()
        chart.plotBackgroundColor = HIColor()
        
        options.colors = COMMON_SHARED.aryStaticColorForChart
        
        let title = HITitle()
        title.text = "MTD Diff"
        title.align = "center"
        title.verticalAlign = "middle"
        title.y = NSNumber(value: 30)
        title.widthAdjust = -500
        
        let plotoptions = HIPlotOptions()
        plotoptions.pie = HIPie()
        plotoptions.pie.allowPointSelect = NSNumber(value: true)
        plotoptions.pie.cursor = "pointer"
        
        let dataLabelsOptionsObject = HIDataLabelsOptionsObject()
        dataLabelsOptionsObject.format = "<b>{point.name}</b>: {point.percentage:.2f}%"
        dataLabelsOptionsObject.style = HICSSObject()
        dataLabelsOptionsObject.style.color = "black"
        plotoptions.pie.startAngle = NSNumber(value: 0)
        plotoptions.pie.endAngle = NSNumber(value: 360)
        plotoptions.pie.center = ["50%", "55%"]
        dataLabelsOptionsObject.enabled = NSNumber(value: false)
        
        let aryParameters = NSMutableArray()
        
            _ = aryShowData.filter { (dicShowData) -> Bool in
                if dicShowData.TitleValue == KEY_MTD_VARIANCE {
                    _ = dicShowData.arySubShowData.filter { (dicSubShowData) -> Bool in
                        if dicSubShowData.Key != "Total" {
                            let titleValue = Double(dicSubShowData.TitleValueWithoutSymbol)
                            let parameters    = NSMutableDictionary()
                            parameters.setValue(NSNumber(value: titleValue ?? 0.0), forKey: "y")
                            parameters.setValue(dicSubShowData.Key, forKey: "name")
                            parameters.setValue(NSNumber(value: titleValue ?? 0.0), forKey: "z")
                            parameters.setValue(COMMON_SHARED.setValueWithCurrencySymbol(floatValue: Float(titleValue ?? 0.0)), forKey: "formatted")
                            parameters.setValue(dicSubShowData.isNegative, forKey: "negative")
                            aryParameters.add(parameters)
                        }
                        return true
                    }
                }
                return true
            }
        
        let tooltip = HITooltip()
        tooltip.headerFormat = ""
        tooltip.pointFormat = "<b><p style=\"font-size:12px\">{point.name}: {point.percentage:.2f}%</p></b>"
        
        let pie = HIPie()
        let data = HIData()
        data.y = NSNumber(value: 0.1)
        pie.innerSize = "70%"
        pie.data = aryParameters as? [Any]
        pie.dataLabels = [dataLabelsOptionsObject]
        
        options.title = title
        options.tooltip = tooltip
        options.plotOptions = plotoptions
        options.series = [pie]
        options.exporting = exporting
        options.title.widthAdjust = -500
        viewFirstCharts.options = options
    }

**Comment by ihnatmoisieiev** [comment] 2019-11-05 08:05
@barotbhavesh I created your chart: 

![Zrzut ekranu 2019-11-5 o 09 02 47](https://user-images.githubusercontent.com/11294008/68189204-3084a280-ffab-11e9-9dfe-9089e1c0666c.png)

But negative values also are displayed (e.g. `Total`):

![Zrzut ekranu 2019-11-5 o 09 02 52](https://user-images.githubusercontent.com/11294008/68189291-4e520780-ffab-11e9-976b-51515d1c228e.png)

**Comment by barotbhavesh** [comment] 2019-11-12 11:33
have you change any in existing code ?

**Comment by ihnatmoisieiev** [comment] 2019-11-13 07:30
@barotbhavesh no, only one thing is `COMMON_SHARED.aryStaticColorForChart `. I haven't set it.

Please, see the code:

```
let options = HIOptions()

let exporting = HIExporting()
exporting.enabled = true

let chart = HIChart()
chart.plotBackgroundColor = HIColor()

let title = HITitle()
title.text = "MTD Diff"
title.align = "center"
title.verticalAlign = "middle"
title.y = NSNumber(value: 30)
title.widthAdjust = -500

let plotoptions = HIPlotOptions()
plotoptions.pie = HIPie()
plotoptions.pie.allowPointSelect = NSNumber(value: true)
plotoptions.pie.cursor = "pointer"

let dataLabelsOptionsObject = HIDataLabelsOptionsObject()
dataLabelsOptionsObject.format = "<b>{point.name}</b>: {point.percentage:.2f}%"
dataLabelsOptionsObject.style = HICSSObject()
dataLabelsOptionsObject.style.color = "black"
plotoptions.pie.startAngle = NSNumber(value: 0)
plotoptions.pie.endAngle = NSNumber(value: 360)
plotoptions.pie.center = ["50%", "55%"]
dataLabelsOptionsObject.enabled = NSNumber(value: false)

let tooltip = HITooltip()
tooltip.headerFormat = ""
tooltip.pointFormat = "<b><p style=\"font-size:12px\">{point.name}: {point.percentage:.2f}%</p></b>"

let pie = HIPie()
let data = HIData()
data.y = NSNumber(value: 0.1)
pie.innerSize = "70%"
pie.data = [["name": "Other","y": 69426.35, "z": 69426.35, "negative": false], ["name": "Parts", "y": 270626.24, "z": 270626.24, "negative": true], ["name": "Labor", "y": 228127.36, "z": 228127.36, "negative": true], ["name": "Oil Disposal Fees", "y": 105.99, "z": 105.99, "negative": false], ["name": "Sales Tax", "y": 18992.62, "z": 18992.62, "negative": true], ["name": "Total", "y": 448213.88, "z": 448213.88, "negative": true]]
pie.dataLabels = [dataLabelsOptionsObject]

options.title = title
options.tooltip = tooltip
options.plotOptions = plotoptions
options.series = [pie]
options.exporting = exporting
options.title.widthAdjust = -500
```

**Comment by ihnatmoisieiev** [comment] 2019-11-22 12:42
@barotbhavesh can I close the issue?

**Comment by barotbhavesh** [comment] 2019-11-26 09:39
In your Demo code also not show negative value 

let options = HIOptions()
        
        let chart = HIChart()
        chart.plotBackgroundColor = HIColor()
        chart.plotBorderWidth = NSNumber()
    //    chart.plotShadow = NSNumber(value: false)
//         let legendStyle = HICSSObject()
//        legendStyle
        
        chart.type = "pie"
        
        let title = HITitle()
        title.text = "Browser market"
        
        let tooltip = HITooltip()
        tooltip.pointFormat = "{series.name}: <b>{point.percentage:.1f}%</b>"
        
        let plotoptions = HIPlotOptions()
        plotoptions.pie = HIPie()
        plotoptions.pie.allowPointSelect = NSNumber(value: true)
        plotoptions.pie.cursor = "pointer"
        plotoptions.pie.showInLegend = NSNumber(value: true)
        let dataLabelsOptionsObject = HIDataLabelsOptionsObject()
        dataLabelsOptionsObject.enabled = NSNumber(value: false)
        
        let pie = HIPie()
        pie.name = "Brands"
        pie.dataLabels = [dataLabelsOptionsObject]
        pie.data = [
            [
                "name": "Microsoft Internet Explorer",
                "y": NSNumber(value: -56.33)
            ],
            [
                "name": "Chrome",
                "y": NSNumber(value: 24.03),
                "sliced": NSNumber(value: true),
                "selected": NSNumber(value: true)
            ],
            [
                "name": "Firefox",
                "y": NSNumber(value: 10.38)
            ],
            [
                "name": "Safari",
                "y": NSNumber(value: 4.77)
            ],
            [
                "name": "Opera",
                "y": NSNumber(value: 0.91)
            ],
            [
                "name": "Proprietary or Undetectable",
                "y": NSNumber(value: 0.2)
            ]
        ]
        
        let legend = HILegend()
        legend.enabled = false
        
        options.legend = legend
        options.chart = chart
        options.title = title
        options.tooltip = tooltip
        options.plotOptions = plotoptions
        options.series = [pie]
        collection.viewCharts.options = options

**Comment by ihnatmoisieiev** [comment] 2019-11-26 20:53
@barotbhavesh you haven't set `negative` param for **Microsoft Internet Explorer** data.
Please see the [example](https://github.com/highcharts/highcharts-ios/issues/256#issuecomment-553276090) above.

**Comment by barotbhavesh** [comment] 2019-11-28 04:57
@ihnatmoisieiev please check your demo code 
I am set negative value  
**[ "name": "Microsoft Internet Explorer", "y": NSNumber(value: -56.33)]**

 let options = HIOptions()
        
        let chart = HIChart()
        chart.plotBackgroundColor = HIColor()
        chart.plotBorderWidth = NSNumber()
        chart.plotShadow = HICSSObject()
        
        //         let legendStyle = HICSSObject()
//        legendStyle
        
        chart.type = "pie"
        
        let title = HITitle()
        title.text = "Browser market"
        
        let tooltip = HITooltip()
        tooltip.pointFormat = "{series.name}: <b>{point.percentage:.1f}%</b>"
        
        let plotoptions = HIPlotOptions()
        plotoptions.pie = HIPie()
        plotoptions.pie.allowPointSelect = NSNumber(value: true)
        plotoptions.pie.cursor = "pointer"
        plotoptions.pie.showInLegend = NSNumber(value: true)
        let dataLabelsOptionsObject = HIDataLabelsOptionsObject()
        dataLabelsOptionsObject.enabled = NSNumber(value: false)
        
        let pie = HIPie()
        pie.name = "Brands"
        pie.dataLabels = [dataLabelsOptionsObject]
        pie.data = [
            [
                "name": "Microsoft Internet Explorer",
                "y": NSNumber(value: -56.33)
            ],
            [
                "name": "Chrome",
                "y": NSNumber(value: 24.03),
                "sliced": NSNumber(value: true),
                "selected": NSNumber(value: true)
            ],
            [
                "name": "Firefox",
                "y": NSNumber(value: 10.38)
            ],
            [
                "name": "Safari",
                "y": NSNumber(value: 4.77)
            ],
            [
                "name": "Opera",
                "y": NSNumber(value: 0.91)
            ],
            [
                "name": "Proprietary or Undetectable",
                "y": NSNumber(value: 0.2)
            ]
        ]
        
        let legend = HILegend()
        legend.enabled = false
        
        options.legend = legend
        options.chart = chart
        options.title = title
        options.tooltip = tooltip
        options.plotOptions = plotoptions
        options.series = [pie]
        collection.viewCharts.options = options

but not show negative value in **PIE CHART**
![Simulator Screen Shot - iPhone 5s - 2019-11-28 at 10 27 21](https://user-images.githubusercontent.com/48505333/69778263-ac989180-11c9-11ea-90f9-8741ac09559c.png)

**Comment by sebastianbochan** [comment] 2019-11-28 09:25
Hi @barotbhavesh,
Highcharts library draws chart according to maths rules which does not cover negative values in pie chart. Its physically impossible, so if you would like to do that, you can use a hack:
1. draw all values as positive
2. Use `tooltip.formatter` and `datalabels.formatter` to add minus sign for particular value.

Im closing this ticket because its not a bug.

**Closed by sebastianbochan** 2019-11-28 09:25 UTC
