### ISSUE TITLE
how to display the Value in short Form Like 2M.. 3K... format in tooltip?

### ISSUE THREAD

**Issue by barotbhavesh** [highcharts/highcharts-ios#304] opened 2020-04-21 11:06 UTC
I need to display the amount in US Format same like web portal 

![Screenshot 2020-04-21 at 4 25 49 PM](https://user-images.githubusercontent.com/48505333/79858984-e9ba2600-83ed-11ea-90d2-9c57afe3e594.png)
![Screenshot 2020-04-21 at 4 25 42 PM](https://user-images.githubusercontent.com/48505333/79859250-59c8ac00-83ee-11ea-8492-c3512c8ff17d.png)

so can you please share the code to display tooltip value the same as the web portal.

**Comment by ihnatmoisieiev** [comment] 2020-04-21 12:53
Hello @barotbhavesh,

please check `tooltip.pointFormat` [docs](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/pointFormat).

**Comment by barotbhavesh** [comment] 2020-04-23 05:01
Can you share with me the code I am trying but not get success?

**Comment by ihnatmoisieiev** [comment] 2020-04-23 14:07
@barotbhavesh please `tooltip.pointFormat = "$ {point.y}"`

**Comment by barotbhavesh** [comment] 2020-04-24 06:22
In need to Show like **$2.3M** or **$2k**.

**Comment by ihnatmoisieiev** [comment] 2020-04-24 10:08
@barotbhavesh please check https://github.com/highcharts/highcharts-ios/issues/275

**Comment by barotbhavesh** [comment] 2020-04-24 10:52
let tooltip = HITooltip()
tooltip.formatter = HIFunction(jsFunction: "function () { var axis = this.series.yAxis; return axis.defaultLabelFormatter.call({ axis: axis, value: this.y, chart: axis.chart }); }")
options.tooltip = tooltip

I tried this code but it does not work.

**Comment by ihnatmoisieiev** [comment] 2020-04-24 10:59
@barotbhavesh did you set `yAxis.type = "logarithmic"`?

**Comment by barotbhavesh** [comment] 2020-04-26 12:33
@ihnatmoisieiev Yes, I was.

**Comment by ihnatmoisieiev** [comment] 2020-04-27 08:58
@barotbhavesh please share your chart's options.

**Comment by barotbhavesh** [comment] 2020-04-27 09:03
let options = HIOptions()
        options.colors = aryChartColor
        options.chart = chart
        options.title = title
        options.xAxis = [xaxis]
        options.yAxis = [yaxis]
        options.tooltip = tooltip
        options.series = aryHIColumn
        options.exporting = exporting
        viewFirstCharts.options = options

**Comment by ihnatmoisieiev** [comment] 2020-04-27 09:13
@barotbhavesh please share your full chart config including all data.

**Comment by barotbhavesh** [comment] 2020-04-27 11:05
var aryXCategoryName  = [String]()
        var arySeriesName     = [String]()
        var aryChartColor     = [String]()
        var aryDataForChart   = [Array<Any>]()
        var aryDicValue       = [NSNumber]()
        var aryHIColumn       = [HIColumn]()
        
        lblFirstChartTitle.font = Fonts_OpenSans_Semi_Bold(fontSize: FONT_SIZE_13)
        lblFirstChartTitle.textColor = COMMON_SHARED.colorWithAlpha(UIColor.black, alphaComponent: 0.54)
        lblSecondChartTitle.font = Fonts_OpenSans_Semi_Bold(fontSize: FONT_SIZE_13)
        lblSecondChartTitle.textColor = COMMON_SHARED.colorWithAlpha(UIColor.black, alphaComponent: 0.54)
        
        arySplitString = COMMON_SHARED.strDateValue.components(separatedBy: "/")
        let date = COMMON_SHARED.convertStringDateFormaterInDate(COMMON_SHARED.strDateValue, StrDefultDateFormat: DATE_FORMAT_MM_YY, strConvertDateFormat: DATE_FORMAT_MMM)
        let strSelectMonth = COMMON_SHARED.convertStaticDateFormaterInString(date, StrYearDateFormat: DATE_FORMAT_YY, StrMonthDateFormat: DATE_FORMAT_MMM, strMiddleFormat: "\'")
        
        let exporting = HIExporting()
        exporting.enabled = false
        
        let title = HITitle()
        title.text = ""
        
        let chart = HIChart()
        chart.type = "column"
        chart.events = HIEvents()
        chart.events.load = HIFunction(jsFunction: "function () { this.xAxis[0].update({ labels: { autoRotation: false } }); }")
        chart.plotBackgroundColor = HIColor()
        chart.backgroundColor = HIColor(uiColor: UIColor.clear)
        
        _ = aryFinancialAnalysis.filter { (dicFinancialAnalysis) -> Bool in
            _ = dicFinancialAnalysis.aryFADataModel.filter { (dicFAData) -> Bool in
                _ = dicFAData.aryFASubDataModel.filter { (dicFASubData) -> Bool in
                    aryXCategoryName.append(dicFinancialAnalysis.key)
                    if dicFASubData.key != "Total" && dicFAData.key == strSelectMonth {
                        arySeriesName.append((dicFASubData.key))
                    }
                    return true
                }
                return true
            }
            return true
        }
        
        arySeriesName = COMMON_SHARED.uniq(source: arySeriesName)
        aryXCategoryName = COMMON_SHARED.uniq(source: aryXCategoryName)
        lblFirstChartTitle.text = strSelectMonth
        
        _ = arySeriesName.filter { (dicSeriesName) -> Bool in
            aryDicValue.removeAll()
            _ = aryFinancialAnalysis.filter { (dicFinancialAnalysis) -> Bool in
                _ = dicFinancialAnalysis.aryFADataModel.filter { (dicFAData) -> Bool in
                    _ = dicFAData.aryFASubDataModel.filter { (dicFASubData) -> Bool in
                        if dicFASubData.key != "Total" && dicSeriesName == dicFASubData.key && dicFAData.key == strSelectMonth {
                            if strReportType == "1" {
                                aryDicValue.append(NSNumber(value: dicFASubData.value))
                            } else if strReportType == "2" || strReportType == "8" {
                                aryDicValue.append(NSNumber(value: dicFASubData.fltPercentage))
                            }
                            aryChartColor.append(dicFASubData.color)
                        }
                        return true
                    }
                    return true
                }
                return true
            }
            aryDataForChart.append(aryDicValue)
            return true
        }
        
        aryChartColor = COMMON_SHARED.uniq(source: aryChartColor)
        let xAxis = HIXAxis()
        xAxis.categories = aryXCategoryName
        
        let yAxis = HIYAxis()
        yAxis.title = HITitle()
        yAxis.labels = HILabels()
        //yAxis.type = "logarithmic"
        
        if strReportType == "2" || strReportType == "8" {
            yAxis.labels.format = "{value}%"
        }
        
        let tooltip = HITooltip()
        tooltip.headerFormat = "<b>{point.x}</b><br/>"
        
        if strReportType == "1" {
            yAxis.title.text = "Revenue $"
            tooltip.pointFormat = "<b>{series.name} : ${point.y:.2f}</b><br/>"
        } else if strReportType == "2" {
            yAxis.title.text = "% of sales"
            tooltip.pointFormat = "<b>{series.name} : {point.y:.2f}%</b><br/>"
        } else if strReportType == "8" {
            yAxis.title.text = "GP %"
            tooltip.pointFormat = "<b>{series.name} : {point.y:.2f}%</b><br/>"
        }
        
//        tooltip.formatter = HIFunction(jsFunction: "function () { var axis = this.series.yAxis; return axis.defaultLabelFormatter.call({ axis: axis, value: this.y, chart: axis.chart }); }")
//
        
        //         let plotOptions = HIPlotOptions()
        //         plotOptions.series = HISeries()
        //
        //        let dataLabels = HIDataLabels()
        //        dataLabels.enabled = true
        //        dataLabels.rotation = 270
        //        dataLabels.y = -15
        
        for i in 0 ..< aryDataForChart.count {
            let column = HIColumn()
            column.data = aryDataForChart[i]
            column.name = arySeriesName[i]
            column.stacking = "normal"
            aryHIColumn.append(column)
        }
        
        //plotOptions.series.dataLabels = [dataLabels]
        
        let options = HIOptions()
        //options.plotOptions = plotOptions
        options.colors = aryChartColor
        options.chart = chart
        options.title = title
        options.xAxis = [xAxis]
        options.yAxis = [yAxis]
        options.tooltip = tooltip
        options.series = aryHIColumn
        options.exporting = exporting
        viewFirstCharts.options = options


**With Response**

{"Message":"","ResponseStatus":true,"ErrorData":null,"ResponseData":[{"key":"Auto Expert LLC Avg","data":[{"key":"Apr'20","isDetailTransacion":false,"data":[{"percentage":64.21,"color":"#f3ba17","key":"Parts","value":14516.06},{"percentage":35.79,"color":"#114b91","key":"Labor","value":8091.93},{"percentage":0,"color":"#26afe0","key":"Other","value":0},{"percentage":0,"color":"#007275","key":"Unclassified","value":0},{"percentage":100,"color":"#d40d7a","key":"Total","value":22607.99}],"color":"#0096d0","Recommendations":null},{"Recommendations":null,"color":null,"isDetailTransacion":false,"key":"Jan'20 - Apr'20 Avg","data":[{"percentage":64.61,"color":"#fdf1d3","value":37967.7,"key":"Parts"},{"percentage":35.39,"color":"#d2ddea","value":20799.33,"key":"Labor"},{"percentage":0,"color":"#d6eff9","value":0,"key":"Other"},{"percentage":0,"color":"#c5e7e8","value":0,"key":"Unclassified"},{"percentage":100,"color":"#f2cbe1","value":58767.03,"key":"Total"}]},{"Recommendations":null,"color":null,"isDetailTransacion":false,"key":"Variance","data":[{"value":-23451.64,"percentage":0,"key":"Parts","color":"#f3ba17"},{"value":-12707.4,"percentage":0,"key":"Labor","color":"#114b91"},{"value":0,"percentage":0,"key":"Other","color":"#26afe0"},{"value":0,"percentage":0,"key":"Unclassified","color":"#007275"},{"value":-36159.04,"percentage":0,"key":"Total","color":"#d40d7a"}]},{"Recommendations":null,"color":null,"isDetailTransacion":false,"key":"Variance %","data":[{"percentage":-61.77,"color":"#f3ba17","key":"Parts","value":0},{"percentage":-61.1,"color":"#114b91","key":"Labor","value":0},{"percentage":0,"color":"#26afe0","key":"Other","value":0},{"percentage":0,"color":"#007275","key":"Unclassified","value":0},{"percentage":-61.53,"color":"#d40d7a","key":"Total","value":0}]}],"companyID":169,"keyID":""}]}

**Comment by ihnatmoisieiev** [comment] 2020-04-27 15:33
@barotbhavesh just use `tooltip.formatter`.
Please see `tooltip.formatter` API [docs](https://api.highcharts.com/ios/highcharts/Classes/HITooltip.html#//api/name/formatter).

In this case, It could be something like:

```
tooltip.formatter = HIFunction(jsFunction: "function() { if (this.y > 1000000) { return '$' + Highcharts.numberFormat(this.y / 1000000, 1) + 'M'; } else if (this.y > 1000) { return '$' + Highcharts.numberFormat(this.y / 1000, 1) + 'k'; } else { return '$' +this.y; } }")
```

**Comment by barotbhavesh** [comment] 2020-05-11 11:58
Please check below screenshot
![Screenshot 2020-05-11 at 5 22 06 PM](https://user-images.githubusercontent.com/48505333/81558912-21dcd500-93ac-11ea-9d4e-9428db6d41da.png)

in the screenshot value below 1000 then tooltip show Like this 
So can you show me it goes to else condition then values show with point 2 digit 
Like if the value is 570.323232323 convert to **570.32**

**Comment by ihnatmoisieiev** [comment] 2020-05-11 12:06
@barotbhavesh you should modify `formatter` function for this case. 

```
tooltip.formatter = HIFunction(jsFunction: "function() { if (this.y > 1000000) { return '$' + Highcharts.numberFormat(this.y / 1000000, 2) + 'M'; } else if (this.y > 1000) { return '$' + Highcharts.numberFormat(this.y / 1000, 2) + 'k'; } else { return '$' + Highcharts.numberFormat(this.y, 2); } }")
```

**Comment by barotbhavesh** [comment] 2020-05-15 06:00
Okay Thanks

In HIYAxis() Not showing short label **Like 25k...30k....25k**
if am using this code 

let yaxis = HIYAxis()
yaxis.title = HITitle()
yaxis.labels = HILabels()
yaxis.labels.format = "${value}"
Please check Below Image 
![Screenshot 2020-05-15 at 11 27 54 AM](https://user-images.githubusercontent.com/48505333/82016652-20a6f300-969f-11ea-81d9-8be455cc6db9.png)

I am not adding this line then I am getting short label value 
yaxis.labels.format = "${value}"

I need to both please share code with me.

**Comment by ihnatmoisieiev** [comment] 2020-05-15 10:56
Duplicate of https://github.com/highcharts/highcharts-ios/issues/275

P.S. in your `yaxis.labels` you have the same formatter as in your `tooltip` (https://github.com/highcharts/highcharts-ios/issues/304#issuecomment-626661181). You can use the same.

**Closed by ihnatmoisieiev** 2020-05-15 10:56 UTC
Labels: question
