### ISSUE TITLE
Accessibility - Focus is not proper while Voice over is on

### ISSUE THREAD

**Issue by Trupti15** [highcharts/highcharts-ios#407] opened 2022-11-22 15:01 UTC
Hi,
I have integrated  highcharts-ios" 10.2.1, for displaying chart type column I facing issues on Accessibility. 
When screen reader reads title, it's not focusing on title, it's focusing somewhere else. 
The focus on the complete bar graph is missing. 
The bars are reading as image. 

Is it the issue exist in iOS, or I have missed anything on configuration.
Thanks

**Comment by ihnatmoisieiev** [comment] 2022-11-23 06:37
Hello @Trupti15,
I've just compared Accessibility  from the web and iOS. They are working exactly the same for me.

Please prepare a small example demo where I can reproduce your issue. 

I used Accessibility Inspector for checking the elements.

<img width="448" alt="Screenshot 2022-11-23 at 07 33 34" src="https://user-images.githubusercontent.com/11294008/203485367-eba1673c-8b14-4969-adff-de59ddc8f717.png">

**Comment by Trupti15** [comment] 2022-11-23 08:50
Hi @ihnatmoisieiev, 
I am getting these issues, please have a look at these screenshots:
<img width="1069" alt="Screenshot 2022-11-23 at 13 32 42" src="https://user-images.githubusercontent.com/13196217/203504710-0a49f074-28b4-451f-9247-dbcb3d8ca621.png">
<img width="1135" alt="Screenshot 2022-11-23 at 13 32 49" src="https://user-images.githubusercontent.com/13196217/203504740-65e48c4b-b55c-4376-9a4b-6cabba648387.png">
<img width="1058" alt="Screenshot 2022-11-23 at 13 33 55" src="https://user-images.githubusercontent.com/13196217/203504749-afbd3cda-643a-4d3a-afc9-35ef9ab4eee6.png">

**Comment by ihnatmoisieiev** [comment] 2022-11-24 07:29
Hello @Trupti15,
could you please share a demo chart configuration that I can paste and reproduce the issue?
Thanks.

**Comment by Trupti15** [comment] 2022-11-24 13:25
Hi @ihnatmoisieiev, please check the code here https://github.com/Trupti15/Highchart-iOS-Demo.

**Comment by ihnatmoisieiev** [comment] 2022-11-24 14:59
@Trupti15,
I ran your example, downloaded the same iOS (15.2) and device, but can't reproduce the issue you attached on your first and second screenshots. Did you add some additional config? Could you please provide steps for reproducing?

<img width="756" alt="Screenshot 2022-11-24 at 15 56 26" src="https://user-images.githubusercontent.com/11294008/203814298-fd0ed648-7a23-4bf8-b225-342eaf3ab006.png">

**Comment by oysteinmoseng** [comment] 2022-11-25 10:19
Hi @Trupti15, if I understand you correctly these are the issues:
- When VoiceOver reads the information about the title and axes, the VoiceOver focus indicator does not match the location of the title and axes on the chart.
- Data points are announced as images (graphics).

This is currently expected behavior, and is generally the same behavior you will find on Highcharts for web. Aligning the focus indicator on titles/axes is a planned enhancement, however.

As for the image roles for the data points, we found in testing that we got the most stable results with different screen readers and browsers using this role. Unfortunately many screen readers / browsers still behave strangely with SVG, so we have to keep compatibility in mind. There are enhancements planned where the user can select custom interaction modes that will not include this announcement, however.

If you wanted to, it would be possible to override the image roles, or set `aria-roledescription` on the points, if you wanted them to announce differently. Here is how we would do this in Highcharts for web, I am sure @ihnatmoisieiev or someone else can help out with the iOS equivalent: https://jsfiddle.net/c5u2txmk/ 

I am closing this for now, but will of course reopen if you have further comments on the case.

**Closed by oysteinmoseng** 2022-11-25 10:19 UTC
