### ISSUE TITLE
Rejected by App Store.

### ISSUE THREAD

**Issue by tmyoda** [highcharts/highcharts-ios#339] opened 2020-09-11 10:33 UTC
Hi, 
 
I just submitted the update to App Sore for review, but it was rejected.
The email is shown below.
```
App Store Connect
 
Dear Developer,

We identified one or more issues with a recent submission for App Store review for your app,  Please correct the following issues, then upload again.

ITMS-90792: Invalid font - There was an error validating the font at 'appname.app/Frameworks/Highcharts.framework/com.highcharts.charts.bundle/fonts/Dosis-SemiBold.woff'. Validation failed.

ITMS-90792: Invalid font - There was an error validating the font at 'appname.app/Frameworks/Highcharts.framework/com.highcharts.charts.bundle/fonts/UnicaOne-Regular.woff'. Validation failed.

ITMS-90792: Invalid font - There was an error validating the font at 'appname.app/Frameworks/Highcharts.framework/com.highcharts.charts.bundle/fonts/Dosis-Regular.woff'. Validation failed.

ITMS-90792: Invalid font - There was an error validating the font at 'appname.app/Frameworks/Highcharts.framework/com.highcharts.charts.bundle/fonts/Signika-Bold.ttf'. Validation failed.

Best regards,

The App Store Team
```

Does anyone know how to solve this problem?

Thanks in Advance

**Comment by skuske** [comment] 2020-09-12 05:20
@tmyoda 

That is really strange. Which version of the Highcharts framework is included with your app?

Yesterday se submitted an update of our own app with the Highcharts framework included (v8.1.2), and it went through app review just like it always did. 

However, if you google ITMS-90792, then you'll find out that the issue is indeed related to the fonts, but it looks like the error is coming from the automated validation of the binary.

I would suggest to re-compile your app and try again. Maybe that fixes it.

**Comment by skuske** [comment] 2020-09-12 05:30
No solution, but others see the same issue. Maybe a bug during app review pre-processing?

https://github.com/swisspol/GCDWebServer/issues/501

https://developer.apple.com/forums/thread/657598

https://github.com/readium/r2-testapp-swift/issues/350

**Comment by skuske** [comment] 2020-09-12 05:34
Another idea: maybe it is Xcode 12 related? @tmyoda Did you compile with Xcode 12?

**Comment by ihnatmoisieiev** [comment] 2020-09-12 05:36
Hello @tmyoda,

please make sure that you are including a framework from the [release](https://github.com/highcharts/highcharts-ios/tree/master/release) folder while uploading the app to the App Store.

Also please try @skuske's suggestions. In the meantime, we will investigate the issue as soon as possible.

@skuske many thanks for your involvement!

**Comment by tmyoda** [comment] 2020-09-13 15:45
@skuske 
Thank you for the many suggestions!

I'm using
Highcharts:  7.1.4
Xcode: 11

I'll re-compile and submit it again for review and then report back to this issue.

**Comment by skuske** [comment] 2020-09-14 09:00
@tmyoda 

I cannot tell you why you might have trouble with v7.1.4 since I am using v8.x for months now and never had any issue like you have. However, maybe Apple changed something during app review pre-processing that affects some apps only, maybe under certain circumstances.

Did you re-compile and if so, did it work now?

**Comment by tmyoda** [comment] 2020-09-16 08:05
@skuske 
I re-compiled and submitted it for review again, but  it was rejected in the same problem...
Next, I'll try removing the font shown in the email.
If it's failed, I'll update v8.x.

**Comment by skuske** [comment] 2020-09-16 08:53
@tmyoda 

I just uploaded to AppStore with Highcharts Wrapper v8.1.2: no issue. The build was properly pre-processed and did not produce any error message about fonts or something. Xcode 12 GM (12A7208).

**Comment by skuske** [comment] 2020-09-21 09:27
@ihnatmoisieiev 

I am now seeing this issue, too. Apple rejects the binary when compiled with Xcode 12. We urgently need a fix for that as we cannot submit any updates now and we can no longer use Xcode 11 due to the required iOS 14 compatibility.

![IMG_6362](https://user-images.githubusercontent.com/12996815/93751342-3bfdae00-fbfd-11ea-93b4-fd37ac52a1bf.PNG)

**Comment by skuske** [comment] 2020-09-21 09:33
@ihnatmoisieiev 

Additional info: I complied with Xcode 12 before (same build) and Apple did not reject it. So, it looks like the internal checks during processing the binary at Apple causes this.

**Comment by tmyoda** [comment] 2020-09-21 11:04
@skuske 
Report: I removed the font, and it accepted.
But, I understood I need to update Xcode version since the required iOS 14 compatibility.

Thank you for the many suggestions. They were very helpful.

**Comment by skuske** [comment] 2020-09-21 11:23
@tmyoda 

Could you please re-open the issue as it has NOT been fixed. Thanks.

**Comment by skuske** [comment] 2020-09-21 11:33
@tmyoda @ihnatmoisieiev 

What I just found out is: I updated to Cocoapods 1.10.1 RC1, recompiled our app, and voila: no issues reported.

**Comment by skuske** [comment] 2020-09-21 11:36
@tmyoda @ihnatmoisieiev

I forgot to mention that I did a 

`pod deintegrate`

followed by a

`pod install`

after updating Cocoapods. Looks like this fixed it. I would suggest to leave this issue open, though, just in case the issue comes back.

**Comment by skuske** [comment] 2020-09-21 12:01
@ihnatmoisieiev 

OK, I was too fast. No luck - Apple rejected the build again. So, we need a proper solution now.

**Comment by skuske** [comment] 2020-09-21 12:06
@ihnatmoisieiev 

Is it safe to just remove those fonts? For what feature of Highcharts are they required for?

**Comment by ihnatmoisieiev** [comment] 2020-09-22 08:13
@tmyoda @skuske 

8.2.1 has been released recently. Could you please update and upload the build again?
Please let us know if it fixes the issue.

**Comment by skuske** [comment] 2020-09-22 08:17
@ihnatmoisieiev 

Will do so asap, haven't had the time yet. Will try to do that later today.

**Comment by skuske** [comment] 2020-09-22 08:27
@ihnatmoisieiev 

Cannot update, will try again later today.

<img width="560" alt="Bildschirmfoto 2020-09-22 um 10 24 22" src="https://user-images.githubusercontent.com/12996815/93859677-36b46800-fcbe-11ea-808d-05d414beef28.png">

**Comment by ihnatmoisieiev** [comment] 2020-09-22 09:47
@skuske 

CDN is down.

https://github.com/CocoaPods/CocoaPods/issues/10078

**Comment by skuske** [comment] 2020-09-23 13:40
@ihnatmoisieiev 

Issue seems to be fixed.

**Comment by ihnatmoisieiev** [comment] 2020-09-28 14:55
@skuske @tmyoda can I close the issue?

**Comment by skuske** [comment] 2020-09-28 14:59
Yes, fixed for me.

**Comment by tmyoda** [comment] 2020-09-28 15:00
Sure.
@skuske  @ihnatmoisieiev  Many Thanks

**Closed** 2020-09-28 17:59 UTC
