### ISSUE TITLE
HIChartView inside scrollview won't start chart animation while tracking or decelerating

### ISSUE THREAD

**Issue by maxydey** [highcharts/highcharts-ios#138] opened 2018-10-15 07:11 UTC
I have highchartView in uitableviewcell. It is provided with HIOptions asynchronously on main thread shortly after cell were displayed. But the chartView won't start animating the graph if the tableview is tracking, or decelerating, even if animation duration is set to zero.

 So the chart is empty until user has released his finger and deceleration has stopped.

**Comment by rradenkov** [comment] 2018-11-21 16:34
Hi @ihnatmoisieiev. I am able to reproduce the same issue when chart is inside table view cell with default table view cell reusing. I updated the DashboardViewController from HighFit swift demo to demonstrate it - https://github.com/rradenkov/highcharts-ios/tree/bug/table-view-scrolling.
Initial animation is disabled so effect can be more clearly seen.

Looking forward for any suggestion from your side.

**Comment by maxydey** [comment] 2019-01-15 11:34
@rradenkov do you have any updates on how to fix this?

**Comment by rradenkov** [comment] 2019-01-15 12:04
No, I didn't get any response from @ihnatmoisieiev or HICharts team 😞

**Comment by ihnatmoisieiev** [comment] 2019-01-15 12:47
Hello @rradenkov @maxydey, thanks for reminding.
I will investigate the issue soon.

**Comment by ihnatmoisieiev** [comment] 2019-01-16 13:21
@maxydey @rradenkov this is a difficult problem and there is no elegant way to solve it, because `HIChartView` loads a chart asynchronously. 

One way to solve it is to implement something like `pagination` and reload `UITableView` after the `n-th` chart is loaded. A `chartViewDidLoad` method from `HIChartViewDelegate` is called when drawing is complete. 

Another option will be added to the framework in the next release. This will fix the issue however this is not recommended and may be unstable. I will inform you what you need to set up.

**Comment by rradenkov** [comment] 2019-01-16 13:34
@ihnatmoisieiev Thanks for the quick response. I have already done what you suggested as workaround. I show loading state for the chart while waiting for `chartViewDidLoad` from the delegate and then show the chart. But this leaves not very pleasant user experience. Because data is there and chart just needs to be redrawn when cell is recycled, but this doesn't happen while UITableView is decelerating or scrolling. Maybe a way to redraw the cell without animation will help.

**Comment by ihnatmoisieiev** [comment] 2019-01-17 10:44
@rradenkov have you tried not to set up `chartView.options` inside `cellForRowAt`? I suppose that's causing the chart to be redrawn.

**Comment by ihnatmoisieiev** [comment] 2019-01-18 08:39
@rradenkov I have understood the problem and suggested a workaround. In another way, I propose you set up your 10 `HIChartView` options before `UITableVew` being initialized. In `tableView(_:cellForRowAt:)` you will only assign previously loaded `HIChartView `, e.g. 
```
cell.chartView = self.charts[indexPath.row]
```
I had it in mind in the previous comment.

**Comment by rradenkov** [comment] 2019-01-18 09:34
@ihnatmoisieiev I got your suggestion. I will try it and see what the effect will be. I hope it doesn't have negative effect on the memory for low powered devices.
Thanks

**Comment by ihnatmoisieiev** [comment] 2019-01-31 11:43
@rradenkov @maxydey a new `synced` param has been added to `HIChartView` in the latest 7.0.2 version. You can 'synchronously' render the chart by setting it to `true`. But please note that usage not recommended and it could be unstable.

**Comment by ihnatmoisieiev** [comment] 2019-02-05 12:59
Can I close the issue?

**Closed** 2019-02-13 06:19 UTC

**Comment by maxydey** [comment] 2019-02-14 16:01
@ihnatmoisieiev sorry it's taking so long to respond.         
setting `HIChartView.synced = true`
doesn't seem to solve the issue

**Comment by ihnatmoisieiev** [comment] 2019-02-18 08:04
Hello @maxydey,
as I have mentioned earlier, this is not an issue and there is no elegant way to solve it. `HIChartView.synced` is only one of the workarounds and it works for me:

![test](https://user-images.githubusercontent.com/11294008/52936326-12fba400-335c-11e9-9a6e-da39be0a5ab1.gif)

**Comment by rradenkov** [comment] 2019-02-19 14:37
Hi @ihnatmoisieiev 
Sorry for the late response, but I was away for a while.
I tried both of the workarounds you suggested:
- using `synced` works when you scroll slowly, but when you fling it fails to update the cells and they remain with the old content
- caching the HIChartViews and setting the appropriate one on `tableView(_:cellForRowAt:)` leads to poor performance when scrolling, sometimes even dropping to few FPS. This is the case when all HIChart views are created beforehand, when creating them on the fly it is even worse.

Do you have any other optimization suggestion?
Thanks
